### ISSUE TITLE
 build on Windows package tinyredis-2.1.1 Error: undefined identifier `EWOULDBLOCK` dmd failed with exit code 1

### ISSUE THREAD

**Issue by jakezrol** [adilbaig/Tiny-Redis#37]
Hi,

I can't build my project because of this error in connection.d about the constant EWOULDBLOCK on windows10.

C:\Users\USER\AppData\Local\dub\packages\tinyredis-2.1.1\tinyredis\source\tinyredis\connection.d(145,30): Error: undefined identifier `EWOULDBLOCK`
dmd failed with exit code 1.    

Is there a way to make it work later?

Thanks

**Comment by adilbaig** [comment]
Hi @jakezrol ,

My apologies for not looking at this much earlier. I don't have any working experience in windows, I assume there is an equivalent to EWOULDBLOCK to Windows 10. I'll have to look this up online, unless you can point me to it? 

Can you double-check for me if it's broken in release v2.2.0?
